<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Fri Apr 12 2019 11:41:27 GMT+0000 (UTC)). */
return array(
	'es6-shim' => '0.35.3',
	'es7-shim' => '6.0.0',
	'i18n-react' => '0.6.4',
	'mobx' => '4.5.1',
	'mobx-state-tree' => '3.5.0',
	'react' => '16.5.2',
	'react-aiot' => '1.3.8',
	'react-dom' => '16.5.2',
	'wp-media-picker' => '0.7.2'
);
