<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Fri Apr 12 2019 11:41:27 GMT+0000 (UTC)). */
return array(
	'public/dist/rml_gutenberg.js' => '2276bbe2e58b278a0147564a55815425',
	'public/dist/rml_shortcode.js' => '160f41bbbee92e21eb2a156974f516f8',
	'public/dist/rml.js' => '38b6edb3c6639ce61c688abfdad8b2e8',
	'public/dist/rml_shortcode.css' => '61ce9c6f338535231d9c1fa874a2597a',
	'public/dist/rml.css' => '85269ee3862d8c5939c905e79b26789d',
	'public/dev/rml_gutenberg.js' => '643070ad14921fcf9ee6aec7665a7e82',
	'public/dev/rml_shortcode.js' => '044f3489cfc38a09fd4c2b66fedc0e84',
	'public/dev/rml.js' => 'ac7e70a3c9050ebbaa0b0e7506fd4a80',
	'public/dev/rml_shortcode.css' => '642261d94bf4fee1670a1df8ed0d6742',
	'public/dev/rml.css' => 'a173ea398ceeca0606a0a9bd4398bb54',
);
